# DO NOT EDIT
# This makefile makes sure all linkable targets are
# up-to-date with anything they link to
default:
	echo "Do not invoke directly"

# For each target create a dummy rule so the target does not have to exist


# Rules to remove targets that are older than anything to which they
# link.  This forces Xcode to relink the targets from scratch.  It
# does not seem to check these dependencies itself.
PostBuild.osgdb_serializers_osg.Debug:
PostBuild.osgdb_serializers_osganimation.Debug:
PostBuild.osgdb_serializers_osgfx.Debug:
PostBuild.osgdb_serializers_osgmanipulator.Debug:
PostBuild.osgdb_serializers_osgparticle.Debug:
PostBuild.osgdb_serializers_osgsim.Debug:
PostBuild.osgdb_serializers_osgshadow.Debug:
PostBuild.osgdb_serializers_osgga.Debug:
PostBuild.osgdb_serializers_osgterrain.Debug:
PostBuild.osgdb_serializers_osgtext.Debug:
PostBuild.osgdb_serializers_osgvolume.Debug:
PostBuild.osgdb_deprecated_osg.Debug:
PostBuild.osgdb_deprecated_osgparticle.Debug:
PostBuild.osgdb_deprecated_osganimation.Debug:
PostBuild.osgdb_deprecated_osgfx.Debug:
PostBuild.osgdb_deprecated_osgsim.Debug:
PostBuild.osgdb_deprecated_osgtext.Debug:
PostBuild.osgdb_deprecated_osgviewer.Debug:
PostBuild.osgdb_deprecated_osgshadow.Debug:
PostBuild.osgdb_deprecated_osgterrain.Debug:
PostBuild.osgdb_deprecated_osgvolume.Debug:
PostBuild.osgdb_deprecated_osgwidget.Debug:
PostBuild.osgdb_osga.Debug:
PostBuild.osgdb_rot.Debug:
PostBuild.osgdb_scale.Debug:
PostBuild.osgdb_trans.Debug:
PostBuild.osgdb_normals.Debug:
PostBuild.osgdb_revisions.Debug:
PostBuild.osgdb_osgviewer.Debug:
PostBuild.osgdb_osgshadow.Debug:
PostBuild.osgdb_osgterrain.Debug:
PostBuild.osgdb_osg.Debug:
PostBuild.osgdb_ive.Debug:
PostBuild.osgdb_cfg.Debug:
PostBuild.osgdb_glsl.Debug:
PostBuild.osgdb_rgb.Debug:
PostBuild.osgdb_bmp.Debug:
PostBuild.osgdb_pnm.Debug:
PostBuild.osgdb_dds.Debug:
PostBuild.osgdb_tga.Debug:
PostBuild.osgdb_hdr.Debug:
PostBuild.osgdb_dot.Debug:
PostBuild.osgdb_vtf.Debug:
PostBuild.osgdb_ktx.Debug:
PostBuild.osgdb_3dc.Debug:
PostBuild.osgdb_p3d.Debug:
PostBuild.osgdb_dw.Debug:
PostBuild.osgdb_bvh.Debug:
PostBuild.osgdb_x.Debug:
PostBuild.osgdb_dxf.Debug:
PostBuild.osgdb_openflight.Debug:
PostBuild.osgdb_geo.Debug:
PostBuild.osgdb_obj.Debug:
PostBuild.osgdb_pic.Debug:
PostBuild.osgdb_stl.Debug:
PostBuild.osgdb_3ds.Debug:
PostBuild.osgdb_ac.Debug:
PostBuild.osgdb_pov.Debug:
PostBuild.osgdb_logo.Debug:
PostBuild.osgdb_lws.Debug:
PostBuild.osgdb_md2.Debug:
PostBuild.osgdb_osgtgz.Debug:
PostBuild.osgdb_tgz.Debug:
PostBuild.osgdb_shp.Debug:
PostBuild.osgdb_txf.Debug:
PostBuild.osgdb_bsp.Debug:
PostBuild.osgdb_mdl.Debug:
PostBuild.osgdb_lwo.Debug:
PostBuild.osgdb_ply.Debug:
PostBuild.osgdb_txp.Debug:
PostBuild.osgdb_imageio.Debug:
PostBuild.osgdb_freetype.Debug:
PostBuild.osgdb_pvr.Debug:
PostBuild.osgdb_serializers_osg.Release:
PostBuild.osgdb_serializers_osganimation.Release:
PostBuild.osgdb_serializers_osgfx.Release:
PostBuild.osgdb_serializers_osgmanipulator.Release:
PostBuild.osgdb_serializers_osgparticle.Release:
PostBuild.osgdb_serializers_osgsim.Release:
PostBuild.osgdb_serializers_osgshadow.Release:
PostBuild.osgdb_serializers_osgga.Release:
PostBuild.osgdb_serializers_osgterrain.Release:
PostBuild.osgdb_serializers_osgtext.Release:
PostBuild.osgdb_serializers_osgvolume.Release:
PostBuild.osgdb_deprecated_osg.Release:
PostBuild.osgdb_deprecated_osgparticle.Release:
PostBuild.osgdb_deprecated_osganimation.Release:
PostBuild.osgdb_deprecated_osgfx.Release:
PostBuild.osgdb_deprecated_osgsim.Release:
PostBuild.osgdb_deprecated_osgtext.Release:
PostBuild.osgdb_deprecated_osgviewer.Release:
PostBuild.osgdb_deprecated_osgshadow.Release:
PostBuild.osgdb_deprecated_osgterrain.Release:
PostBuild.osgdb_deprecated_osgvolume.Release:
PostBuild.osgdb_deprecated_osgwidget.Release:
PostBuild.osgdb_osga.Release:
PostBuild.osgdb_rot.Release:
PostBuild.osgdb_scale.Release:
PostBuild.osgdb_trans.Release:
PostBuild.osgdb_normals.Release:
PostBuild.osgdb_revisions.Release:
PostBuild.osgdb_osgviewer.Release:
PostBuild.osgdb_osgshadow.Release:
PostBuild.osgdb_osgterrain.Release:
PostBuild.osgdb_osg.Release:
PostBuild.osgdb_ive.Release:
PostBuild.osgdb_cfg.Release:
PostBuild.osgdb_glsl.Release:
PostBuild.osgdb_rgb.Release:
PostBuild.osgdb_bmp.Release:
PostBuild.osgdb_pnm.Release:
PostBuild.osgdb_dds.Release:
PostBuild.osgdb_tga.Release:
PostBuild.osgdb_hdr.Release:
PostBuild.osgdb_dot.Release:
PostBuild.osgdb_vtf.Release:
PostBuild.osgdb_ktx.Release:
PostBuild.osgdb_3dc.Release:
PostBuild.osgdb_p3d.Release:
PostBuild.osgdb_dw.Release:
PostBuild.osgdb_bvh.Release:
PostBuild.osgdb_x.Release:
PostBuild.osgdb_dxf.Release:
PostBuild.osgdb_openflight.Release:
PostBuild.osgdb_geo.Release:
PostBuild.osgdb_obj.Release:
PostBuild.osgdb_pic.Release:
PostBuild.osgdb_stl.Release:
PostBuild.osgdb_3ds.Release:
PostBuild.osgdb_ac.Release:
PostBuild.osgdb_pov.Release:
PostBuild.osgdb_logo.Release:
PostBuild.osgdb_lws.Release:
PostBuild.osgdb_md2.Release:
PostBuild.osgdb_osgtgz.Release:
PostBuild.osgdb_tgz.Release:
PostBuild.osgdb_shp.Release:
PostBuild.osgdb_txf.Release:
PostBuild.osgdb_bsp.Release:
PostBuild.osgdb_mdl.Release:
PostBuild.osgdb_lwo.Release:
PostBuild.osgdb_ply.Release:
PostBuild.osgdb_txp.Release:
PostBuild.osgdb_imageio.Release:
PostBuild.osgdb_freetype.Release:
PostBuild.osgdb_pvr.Release:
PostBuild.osgdb_serializers_osg.MinSizeRel:
PostBuild.osgdb_serializers_osganimation.MinSizeRel:
PostBuild.osgdb_serializers_osgfx.MinSizeRel:
PostBuild.osgdb_serializers_osgmanipulator.MinSizeRel:
PostBuild.osgdb_serializers_osgparticle.MinSizeRel:
PostBuild.osgdb_serializers_osgsim.MinSizeRel:
PostBuild.osgdb_serializers_osgshadow.MinSizeRel:
PostBuild.osgdb_serializers_osgga.MinSizeRel:
PostBuild.osgdb_serializers_osgterrain.MinSizeRel:
PostBuild.osgdb_serializers_osgtext.MinSizeRel:
PostBuild.osgdb_serializers_osgvolume.MinSizeRel:
PostBuild.osgdb_deprecated_osg.MinSizeRel:
PostBuild.osgdb_deprecated_osgparticle.MinSizeRel:
PostBuild.osgdb_deprecated_osganimation.MinSizeRel:
PostBuild.osgdb_deprecated_osgfx.MinSizeRel:
PostBuild.osgdb_deprecated_osgsim.MinSizeRel:
PostBuild.osgdb_deprecated_osgtext.MinSizeRel:
PostBuild.osgdb_deprecated_osgviewer.MinSizeRel:
PostBuild.osgdb_deprecated_osgshadow.MinSizeRel:
PostBuild.osgdb_deprecated_osgterrain.MinSizeRel:
PostBuild.osgdb_deprecated_osgvolume.MinSizeRel:
PostBuild.osgdb_deprecated_osgwidget.MinSizeRel:
PostBuild.osgdb_osga.MinSizeRel:
PostBuild.osgdb_rot.MinSizeRel:
PostBuild.osgdb_scale.MinSizeRel:
PostBuild.osgdb_trans.MinSizeRel:
PostBuild.osgdb_normals.MinSizeRel:
PostBuild.osgdb_revisions.MinSizeRel:
PostBuild.osgdb_osgviewer.MinSizeRel:
PostBuild.osgdb_osgshadow.MinSizeRel:
PostBuild.osgdb_osgterrain.MinSizeRel:
PostBuild.osgdb_osg.MinSizeRel:
PostBuild.osgdb_ive.MinSizeRel:
PostBuild.osgdb_cfg.MinSizeRel:
PostBuild.osgdb_glsl.MinSizeRel:
PostBuild.osgdb_rgb.MinSizeRel:
PostBuild.osgdb_bmp.MinSizeRel:
PostBuild.osgdb_pnm.MinSizeRel:
PostBuild.osgdb_dds.MinSizeRel:
PostBuild.osgdb_tga.MinSizeRel:
PostBuild.osgdb_hdr.MinSizeRel:
PostBuild.osgdb_dot.MinSizeRel:
PostBuild.osgdb_vtf.MinSizeRel:
PostBuild.osgdb_ktx.MinSizeRel:
PostBuild.osgdb_3dc.MinSizeRel:
PostBuild.osgdb_p3d.MinSizeRel:
PostBuild.osgdb_dw.MinSizeRel:
PostBuild.osgdb_bvh.MinSizeRel:
PostBuild.osgdb_x.MinSizeRel:
PostBuild.osgdb_dxf.MinSizeRel:
PostBuild.osgdb_openflight.MinSizeRel:
PostBuild.osgdb_geo.MinSizeRel:
PostBuild.osgdb_obj.MinSizeRel:
PostBuild.osgdb_pic.MinSizeRel:
PostBuild.osgdb_stl.MinSizeRel:
PostBuild.osgdb_3ds.MinSizeRel:
PostBuild.osgdb_ac.MinSizeRel:
PostBuild.osgdb_pov.MinSizeRel:
PostBuild.osgdb_logo.MinSizeRel:
PostBuild.osgdb_lws.MinSizeRel:
PostBuild.osgdb_md2.MinSizeRel:
PostBuild.osgdb_osgtgz.MinSizeRel:
PostBuild.osgdb_tgz.MinSizeRel:
PostBuild.osgdb_shp.MinSizeRel:
PostBuild.osgdb_txf.MinSizeRel:
PostBuild.osgdb_bsp.MinSizeRel:
PostBuild.osgdb_mdl.MinSizeRel:
PostBuild.osgdb_lwo.MinSizeRel:
PostBuild.osgdb_ply.MinSizeRel:
PostBuild.osgdb_txp.MinSizeRel:
PostBuild.osgdb_imageio.MinSizeRel:
PostBuild.osgdb_freetype.MinSizeRel:
PostBuild.osgdb_pvr.MinSizeRel:
PostBuild.osgdb_serializers_osg.RelWithDebInfo:
PostBuild.osgdb_serializers_osganimation.RelWithDebInfo:
PostBuild.osgdb_serializers_osgfx.RelWithDebInfo:
PostBuild.osgdb_serializers_osgmanipulator.RelWithDebInfo:
PostBuild.osgdb_serializers_osgparticle.RelWithDebInfo:
PostBuild.osgdb_serializers_osgsim.RelWithDebInfo:
PostBuild.osgdb_serializers_osgshadow.RelWithDebInfo:
PostBuild.osgdb_serializers_osgga.RelWithDebInfo:
PostBuild.osgdb_serializers_osgterrain.RelWithDebInfo:
PostBuild.osgdb_serializers_osgtext.RelWithDebInfo:
PostBuild.osgdb_serializers_osgvolume.RelWithDebInfo:
PostBuild.osgdb_deprecated_osg.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgparticle.RelWithDebInfo:
PostBuild.osgdb_deprecated_osganimation.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgfx.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgsim.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgtext.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgviewer.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgshadow.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgterrain.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgvolume.RelWithDebInfo:
PostBuild.osgdb_deprecated_osgwidget.RelWithDebInfo:
PostBuild.osgdb_osga.RelWithDebInfo:
PostBuild.osgdb_rot.RelWithDebInfo:
PostBuild.osgdb_scale.RelWithDebInfo:
PostBuild.osgdb_trans.RelWithDebInfo:
PostBuild.osgdb_normals.RelWithDebInfo:
PostBuild.osgdb_revisions.RelWithDebInfo:
PostBuild.osgdb_osgviewer.RelWithDebInfo:
PostBuild.osgdb_osgshadow.RelWithDebInfo:
PostBuild.osgdb_osgterrain.RelWithDebInfo:
PostBuild.osgdb_osg.RelWithDebInfo:
PostBuild.osgdb_ive.RelWithDebInfo:
PostBuild.osgdb_cfg.RelWithDebInfo:
PostBuild.osgdb_glsl.RelWithDebInfo:
PostBuild.osgdb_rgb.RelWithDebInfo:
PostBuild.osgdb_bmp.RelWithDebInfo:
PostBuild.osgdb_pnm.RelWithDebInfo:
PostBuild.osgdb_dds.RelWithDebInfo:
PostBuild.osgdb_tga.RelWithDebInfo:
PostBuild.osgdb_hdr.RelWithDebInfo:
PostBuild.osgdb_dot.RelWithDebInfo:
PostBuild.osgdb_vtf.RelWithDebInfo:
PostBuild.osgdb_ktx.RelWithDebInfo:
PostBuild.osgdb_3dc.RelWithDebInfo:
PostBuild.osgdb_p3d.RelWithDebInfo:
PostBuild.osgdb_dw.RelWithDebInfo:
PostBuild.osgdb_bvh.RelWithDebInfo:
PostBuild.osgdb_x.RelWithDebInfo:
PostBuild.osgdb_dxf.RelWithDebInfo:
PostBuild.osgdb_openflight.RelWithDebInfo:
PostBuild.osgdb_geo.RelWithDebInfo:
PostBuild.osgdb_obj.RelWithDebInfo:
PostBuild.osgdb_pic.RelWithDebInfo:
PostBuild.osgdb_stl.RelWithDebInfo:
PostBuild.osgdb_3ds.RelWithDebInfo:
PostBuild.osgdb_ac.RelWithDebInfo:
PostBuild.osgdb_pov.RelWithDebInfo:
PostBuild.osgdb_logo.RelWithDebInfo:
PostBuild.osgdb_lws.RelWithDebInfo:
PostBuild.osgdb_md2.RelWithDebInfo:
PostBuild.osgdb_osgtgz.RelWithDebInfo:
PostBuild.osgdb_tgz.RelWithDebInfo:
PostBuild.osgdb_shp.RelWithDebInfo:
PostBuild.osgdb_txf.RelWithDebInfo:
PostBuild.osgdb_bsp.RelWithDebInfo:
PostBuild.osgdb_mdl.RelWithDebInfo:
PostBuild.osgdb_lwo.RelWithDebInfo:
PostBuild.osgdb_ply.RelWithDebInfo:
PostBuild.osgdb_txp.RelWithDebInfo:
PostBuild.osgdb_imageio.RelWithDebInfo:
PostBuild.osgdb_freetype.RelWithDebInfo:
PostBuild.osgdb_pvr.RelWithDebInfo:
